import { Section, Eyebrow, CountUp, useT, useReveal } from "./lang";

function StatementCard({
  title,
  rows,
  footer,
}: {
  title: string;
  rows: { label: string; value: string; strong?: boolean }[];
  footer?: string;
}) {
  return (
    <div className="card-soft min-w-[280px] flex-1 overflow-hidden">
      <div className="border-b border-hairline bg-surface-2/70 px-4 py-3 text-[13px] font-semibold text-ink">
        {title}
      </div>
      <div className="divide-y divide-hairline">
        {rows.map((r) => (
          <div
            key={r.label}
            className={`flex items-center justify-between gap-4 px-4 py-3 text-[13px] ${
              r.strong ? "bg-surface-2/50 font-semibold text-ink" : "text-muted-foreground"
            }`}
          >
            <span className="min-w-0 truncate">{r.label}</span>
            <span className="num shrink-0 text-ink">{r.value}</span>
          </div>
        ))}
      </div>
      {footer && (
        <div className="border-t border-hairline px-4 py-2.5 text-[11.5px] text-muted-foreground">
          {footer}
        </div>
      )}
    </div>
  );
}

export function Statements() {
  const t = useT();
  return (
    <Section>
      <Eyebrow>{t("القوائم المالية", "Financial statements")}</Eyebrow>
      <h2 className="mt-4 text-[28px] leading-[1.35] font-bold text-ink sm:text-[36px]">
        {t("افهم الوضع المالي لشركتك فورًا", "See your company's financial position immediately")}
      </h2>

      <div className="-mx-5 mt-10 flex snap-x gap-4 overflow-x-auto px-5 pb-3 sm:mx-0 sm:px-0 lg:overflow-visible">
        <StatementCard
          title={t("قائمة الدخل", "Income statement")}
          rows={[
            { label: t("الإيرادات", "Revenue"), value: "4,820,000" },
            { label: t("تكلفة المبيعات", "Cost of sales"), value: "(3,084,800)" },
            { label: t("مجمل الربح", "Gross profit"), value: "1,735,200", strong: true },
            { label: t("المصروفات", "Expenses"), value: "(1,122,800)" },
            { label: t("صافي الربح", "Net profit"), value: "612,400", strong: true },
          ]}
          footer={t("SAR · مارس 2026", "SAR · March 2026")}
        />
        <StatementCard
          title={t("الميزانية العمومية", "Balance sheet")}
          rows={[
            { label: t("الأصول", "Assets"), value: "9,410,000", strong: true },
            { label: t("الأصول المتداولة", "Current assets"), value: "4,120,000" },
            { label: t("الالتزامات", "Liabilities"), value: "3,860,000", strong: true },
            { label: t("الالتزامات المتداولة", "Current liabilities"), value: "2,238,000" },
            { label: t("حقوق الملكية", "Equity"), value: "5,550,000", strong: true },
          ]}
          footer="Assets = Liabilities + Equity ✓"
        />
        <StatementCard
          title={t("المؤشرات المالية", "Financial metrics")}
          rows={[
            { label: t("هامش الربح", "Gross margin"), value: "36.0%" },
            { label: t("هامش التشغيل", "Operating margin"), value: "18.4%" },
            { label: t("هامش صافي الربح", "Net margin"), value: "12.7%" },
            { label: "Current Ratio", value: "1.84" },
            { label: "Working Capital", value: "1,882,000" },
          ]}
          footer={t("محسوبة من Financial Truth", "Calculated from Financial Truth")}
        />
      </div>
    </Section>
  );
}

export function CashFlow() {
  const t = useT();
  const { ref, visible } = useReveal<HTMLDivElement>();
  const activities = [
    {
      t: t("التدفقات النقدية من الأنشطة التشغيلية", "Cash from operating activities"),
      s: "Operating",
      d: t(
        "اعرف مقدار النقد الناتج عن النشاط الأساسي للشركة.",
        "See how much cash the core business actually generates.",
      ),
      v: "+ 1,240,000",
      pos: true,
    },
    {
      t: t("التدفقات النقدية من الأنشطة الاستثمارية", "Cash from investing activities"),
      s: "Investing",
      d: t(
        "تابع النقد المستخدم أو الناتج عن الاستثمارات وشراء وبيع الأصول.",
        "Track cash used or generated by investments and asset purchases or sales.",
      ),
      v: "(480,000)",
      pos: false,
    },
    {
      t: t("التدفقات النقدية من الأنشطة التمويلية", "Cash from financing activities"),
      s: "Financing",
      d: t(
        "افهم تأثير القروض، التمويل، رأس المال، والتوزيعات على السيولة.",
        "Understand how loans, capital, and distributions affect liquidity.",
      ),
      v: "(210,000)",
      pos: false,
    },
  ];
  const flows = [
    { l: t("التدفق النقدي التشغيلي", "Operating cash flow"), v: "1,240,000" },
    { l: t("التدفق النقدي الاستثماري", "Investing cash flow"), v: "(480,000)" },
    { l: t("التدفق النقدي التمويلي", "Financing cash flow"), v: "(210,000)" },
    { l: t("صافي التغير في النقد", "Net change in cash"), v: "550,000", strong: true },
  ];

  return (
    <Section id="cashflow">
      <Eyebrow>{t("قائمة التدفقات النقدية", "Cash flow statement")}</Eyebrow>
      <h2 className="mt-4 max-w-[26ch] text-[28px] leading-[1.35] font-bold text-ink sm:text-[36px]">
        {t("اعرف من أين يأتي النقد وإلى أين يذهب.", "See where cash comes from and where it goes.")}
      </h2>
      <p className="mt-4 max-w-[64ch] text-[15px] leading-8 text-muted-foreground">
        {t(
          "لا يكفي أن تعرف أن شركتك تحقق أرباحًا. التدفق النقدي يوضح لك كيف تتحرك السيولة الفعلية داخل الشركة، وما إذا كانت العمليات تحقق نقدًا أم تستهلكه.",
          "Profit is not enough. Cash flow shows how liquidity actually moves inside the company, and whether operations generate cash or consume it.",
        )}
      </p>

      <div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-hairline bg-hairline lg:grid-cols-3">
        {activities.map((a) => (
          <div key={a.s} className="bg-surface p-6">
            <div className="num text-[11px] font-semibold tracking-widest text-teal uppercase">
              {a.s}
            </div>
            <h3 className="mt-2 text-[15px] leading-7 font-semibold text-ink">{a.t}</h3>
            <p className="mt-2 text-[13.5px] leading-7 text-muted-foreground">{a.d}</p>
            <div
              className={`num mt-4 text-[18px] font-semibold ${a.pos ? "text-positive" : "text-danger"}`}
            >
              {a.v}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_1fr]">
        <div className="card-soft flex flex-col justify-center p-6 sm:p-8">
          <div className="text-[13px] font-semibold text-ink">
            {t("صافي التدفق النقدي", "Net cash flow")}
          </div>
          <p className="mt-3 text-[14px] leading-8 text-muted-foreground">
            {t("النقد الداخل", "Cash in")} <span className="num">−</span> {t("النقد الخارج", "cash out")} ={" "}
            {t("صافي التغير في النقد", "net change in cash")}
          </p>
          <p className="mt-5 border-s-2 border-teal ps-4 text-[14px] leading-7 font-semibold text-ink">
            {t(
              "اربط الأرباح بالسيولة، واعرف ما إذا كانت الشركة تولّد نقدًا فعليًا من نشاطها.",
              "Connect profit to liquidity and see whether the business actually generates cash.",
            )}
          </p>
        </div>

        <div ref={ref} className="card-soft overflow-hidden">
          <div className="border-b border-hairline bg-surface-2/70 px-4 py-3 text-[13px] font-semibold text-ink">
            {t("صافي التدفق النقدي", "Net cash flow")}
          </div>
          <div className="divide-y divide-hairline">
            {flows.map((f, i) => (
              <div
                key={f.l}
                className={`flex items-center justify-between gap-4 px-4 py-3.5 text-[13px] transition-all duration-500 ${
                  f.strong ? "bg-surface-2/50 font-semibold text-ink" : "text-muted-foreground"
                } ${visible ? "translate-y-0 opacity-100" : "translate-y-2 opacity-0"}`}
                style={{ transitionDelay: `${i * 110}ms` }}
              >
                <span className="min-w-0 truncate">{f.l}</span>
                <span className="num shrink-0 text-ink">{f.v}</span>
              </div>
            ))}
          </div>
          <div className="border-t border-hairline px-4 py-2.5 text-[11.5px] text-muted-foreground">
            {t("SAR · محسوبة من Financial Truth", "SAR · calculated from Financial Truth")}
          </div>
        </div>
      </div>
    </Section>
  );
}

function Bars() {
  const { ref, visible } = useReveal<HTMLDivElement>();
  const data = [42, 55, 48, 63, 58, 72, 68, 81];
  return (
    <div ref={ref} className="flex h-28 items-end gap-2">
      {data.map((v, i) => (
        <div key={i} className="flex-1 rounded-t-[3px] bg-surface-2">
          <div
            className="w-full rounded-t-[3px] bg-teal/70 transition-[height] duration-700"
            style={{ height: visible ? `${v}px` : "0px", transitionDelay: `${i * 60}ms` }}
          />
        </div>
      ))}
    </div>
  );
}

export function Analytics() {
  const t = useT();
  return (
    <Section id="analytics">
      <Eyebrow>{t("التحليلات", "Analytics")}</Eyebrow>
      <h2 className="mt-4 text-[28px] leading-[1.35] font-bold text-ink sm:text-[36px]">
        {t("لا تكتفِ بمعرفة الرقم. افهم اتجاهه.", "Don't just know the number. Understand its direction.")}
      </h2>

      <div className="mt-10 grid gap-4 lg:grid-cols-[1.1fr_1fr]">
        <div className="card-soft p-5">
          <div className="flex items-center justify-between">
            <span className="text-[13px] font-semibold text-ink">
              {t("اتجاه الإيرادات والربح", "Revenue & profit trend")}
            </span>
            <span className="num text-[11.5px] text-muted-foreground">Revenue · Profit · Expense</span>
          </div>
          <div className="mt-5">
            <Bars />
          </div>
          <div className="mt-4 grid grid-cols-3 gap-3 border-t border-hairline pt-4">
            {[
              { l: "Revenue trend", v: 9.2 },
              { l: "Profit trend", v: 4.6 },
              { l: "Expense trend", v: 12.0 },
            ].map((m, i) => (
              <div key={m.l}>
                <div className="num text-[11px] text-muted-foreground">{m.l}</div>
                <div
                  className={`mt-1 text-[15px] font-semibold ${i === 2 ? "text-danger" : "text-positive"}`}
                >
                  {i === 2 ? "+" : "+"}
                  <CountUp to={m.v} decimals={1} suffix="%" />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          {[
            { t: t("المقارنة الشهرية", "Month over month"), s: "MoM", d: t("قارن الأداء بين شهر وآخر.", "Compare performance from one month to the next.") },
            { t: t("المقارنة السنوية", "Year over year"), s: "YoY", d: t("قارن الفترة بنفس الفترة من العام السابق.", "Compare the period with the same period last year.") },
            { t: t("تحليل الاتجاهات", "Trend analysis"), s: "Trends", d: t("اتجاه الإيرادات والربح والمصروفات.", "Revenue, profit, and expense trends.") },
            {
              t: t("تحليل المصروفات", "Expense analysis"),
              s: "Expenses",
              d: t("ما الذي يرتفع؟ ما الذي ينخفض؟ ما الذي يؤثر على الربحية؟", "What is rising, falling, and affecting profitability?"),
            },
          ].map((c) => (
            <div key={c.t} className="card-soft p-5">
              <div className="num text-[11px] font-semibold tracking-widest text-teal uppercase">
                {c.s}
              </div>
              <h3 className="mt-2 text-[15px] font-semibold text-ink">{c.t}</h3>
              <p className="mt-1.5 text-[13px] leading-6 text-muted-foreground">{c.d}</p>
            </div>
          ))}
        </div>
      </div>
    </Section>
  );
}

function Gauge({ score }: { score: number }) {
  const t = useT();
  const { ref, visible } = useReveal<HTMLDivElement>();
  const r = 68;
  const c = Math.PI * r;
  return (
    <div ref={ref} className="relative w-full max-w-[240px]">
      <svg viewBox="0 0 160 92" className="w-full">
        <path
          d="M12 84 A68 68 0 0 1 148 84"
          fill="none"
          stroke="var(--surface-2)"
          strokeWidth="10"
          strokeLinecap="round"
        />
        <path
          d="M12 84 A68 68 0 0 1 148 84"
          fill="none"
          stroke="var(--teal)"
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={c}
          strokeDashoffset={visible ? c * (1 - score / 100) : c}
          style={{ transition: "stroke-dashoffset 1.4s cubic-bezier(0.22,1,0.36,1)" }}
        />
      </svg>
      <div className="absolute inset-x-0 bottom-0 text-center">
        <div dir="ltr" className="text-[34px] leading-none font-bold text-ink">
          <CountUp to={score} />
          <span className="text-[16px] text-muted-foreground"> / 100</span>
        </div>
        <div className="mt-1 text-[13px] font-semibold text-positive">{t("جيدة", "Good")}</div>
      </div>
    </div>
  );
}

export function HealthScore() {
  const t = useT();
  const parts = [
    { l: t("الربحية", "Profitability"), v: 82 },
    { l: t("السيولة", "Liquidity"), v: 74 },
    { l: t("النمو", "Growth"), v: 71 },
    { l: t("كفاءة المصروفات", "Expense efficiency"), v: 85 },
  ];
  const { ref, visible } = useReveal<HTMLDivElement>();
  return (
    <Section>
      <Eyebrow>{t("الصحة المالية", "Financial health")}</Eyebrow>
      <h2 className="mt-4 text-[28px] leading-[1.35] font-bold text-ink sm:text-[36px]">
        {t("كيف تبدو صحة شركتك المالية؟", "How healthy is your company financially?")}
      </h2>

      <div className="card-soft mt-10 grid gap-8 p-6 sm:p-9 lg:grid-cols-[auto_minmax(0,1fr)]">
        <div className="flex flex-col items-center justify-center gap-2">
          <span className="text-[13px] font-semibold text-muted-foreground">
            {t("الصحة المالية", "Financial health")}
          </span>
          <Gauge score={78} />
        </div>

        <div ref={ref} className="grid content-center gap-5">
          {parts.map((p, i) => (
            <div key={p.l}>
              <div className="flex items-center justify-between text-[13px]">
                <span className="text-ink">{p.l}</span>
                <span className="num font-semibold text-ink">{p.v}</span>
              </div>
              <div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-surface-2">
                <div
                  className="h-full rounded-full bg-ink transition-[width] duration-1000"
                  style={{ width: visible ? `${p.v}%` : "0%", transitionDelay: `${i * 120}ms` }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      <p className="mt-5 text-[13px] leading-7 text-muted-foreground">
        {t(
          "هذا التقييم يعتمد على مؤشرات مالية قابلة للتفسير، وليس على تخمينات الذكاء الاصطناعي.",
          "This score is based on explainable financial metrics, not AI guesswork.",
        )}
      </p>
    </Section>
  );
}

export function MultiCompany() {
  const t = useT();
  const levels = [ {ar: "مجموعة الشركات", en: "Group of companies"}, {ar: "الشركة", en: "Company"}, {ar: "الفروع", en: "Branches"}, {ar: "الفترات المالية", en: "Financial periods"}, {ar: "البيانات المالية", en: "Financial data"} ];
  const caps = [{ar: "الشركات والفروع", en: "Companies & branches"}, {ar: "إدارة الفروع", en: "Manage branches"}, {ar: "عزل البيانات بين الشركات", en: "Isolate data between companies"}, {ar: "إدارة الفترات المالية", en: "Manage financial periods"}, {ar: "مقارنة الفترات المالية", en: "Compare financial periods"}, {ar: "عرض جميع الفترات المالية", en: "View all financial periods"}, {ar: "مقارنة جميع الفترات المالية", en: "Compare all financial periods"}, {ar: "مقارنة جميع الشركات والفروع", en: "Compare all companies and branches"}];
  return (
    <Section>
      <Eyebrow>{t("الشركات والفروع", "Companies & branches")}</Eyebrow>
      <h2 className="mt-4 text-[28px] leading-[1.35] font-bold text-ink sm:text-[36px]">
        {t("كل شركاتك وفروعك في مكان واحد", "All your companies and branches in one place")}
      </h2>

      <div className="mt-10 grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
        <div className="card-soft p-5">
          {levels.map((l, i) => (
            <div key={i} style={{ paddingInlineStart: `${i * 18}px` }} className="py-1.5">
              <div className="flex items-center gap-2.5">
                {i > 0 && <span className="text-hairline">└</span>}
                <span
                  className={`rounded-lg border px-3 py-2 text-[13px] ${
                    i === 0
                      ? "border-ink bg-ink font-semibold text-primary-foreground"
                      : "border-hairline bg-surface text-ink"
                  }`}
                >
                  {t(l.ar, l.en)}
                </span>
              </div>
            </div>
          ))}
        </div>

        <div className="grid gap-px overflow-hidden rounded-2xl border border-hairline bg-hairline sm:grid-cols-2">
          {caps.map((c, i) => (
            <div key={i} className="bg-surface px-5 py-5 text-[13.5px] font-medium text-ink">
              {t(c.ar, c.en)}
            </div>
          ))}
        </div>
      </div>
    </Section>
  );
}